/*****************************************************
 * PS5 SDK - Libkernel
 * Implements resolving for libkernel.
 ****************************************************/

#define CRT_BUILD
#include <ps5/libkernel.h>

// Functions that are covered by regular headers
_Fn_(int        , fork,                             void);
_Fn_(int        , socket,                           int domain, int type, int protocol);
_Fn_(int        , connect,                          int s, const struct sockaddr *name, socklen_t namelen);
_Fn_(int        , listen,                           int s, int backlog);
_Fn_(int        , bind,                             int s, void* name, int namelen);
_Fn_(int        , getpid,                           void);
_Fn_(uint64_t   , accept,                           void);
_Fn_(int        , access,                           const char *, int);
_Fn_(uint64_t   , blockpool_batch,                  void);
_Fn_(uint64_t   , blockpool_map,                    void);
_Fn_(uint64_t   , blockpool_open,                   void);
_Fn_(uint64_t   , blockpool_unmap,                  void);
_Fn_(uint64_t   , cfsetspeed,                       void);
_Fn_(int        , chdir,                            const char *);
_Fn_(uint64_t   , chflags,                          void);
_Fn_(uint64_t   , chmod,                            void);
_Fn_(int        , clock_getres,                     clockid_t, struct timespec *);
_Fn_(int        , clock_gettime,                    clockid_t, struct timespec *);
_Fn_(int        , clock_settime,                    clockid_t, const struct timespec *);
_Fn_(int        , close,                            int);
_Fn_(uint64_t   , cpuset_getaffinity,               void);
_Fn_(uint64_t   , cpuset_getid,                     void);
_Fn_(uint64_t   , cpuset_setaffinity,               void);
_Fn_(uint64_t   , creat,                            void);
_Fn_(uint64_t   , dlclose,                          void);
_Fn_(uint64_t   , dlerror,                          void);
_Fn_(uint64_t   , dlopen,                           void);
_Fn_(int        , dup,                              int);
_Fn_(int        , dup2,                             int,int);
_Fn_(uint64_t   , dynlib_get_obj_member,            void);
_Fn_(int        , execv,                            const char *, char * const *);
_Fn_(int        , execve,                           const char *, char * const *, char * const *);
_Fn_(int        , execvp,                           const char *, char * const *);
_Fn_(uint64_t   , fchflags,                         void);
_Fn_(uint64_t   , fchmod,                           void);
_Fn_(uint64_t   , fcntl,                            void);
_Fn_(uint64_t   , flock,                            void);
_Fn_(uint64_t   , fstat,                            void);
_Fn_(int        , fsync,                            int);
_Fn_(uint64_t   , fdatasync,                        void);
_Fn_(int        , ftruncate,                        int, __off_t);
_Fn_(uint64_t   , futimes,                          void);
_Fn_(uint64_t   , get_authinfo,                     void);
_Fn_(uint64_t   , get_page_table_stats,             void);
_Fn_(uint64_t   , get_module_info_list,             void);
_Fn_(uint64_t   , get_sdk_compiled_version,         void);
_Fn_(uint64_t   , get_self_auth_info,               void);
_Fn_(uint64_t   , get_vm_map_timestamp,             void);
_Fn_(uint64_t   , getargc,                          void);
_Fn_(uint64_t   , getargv,                          void);
_Fn_(uint64_t   , getcontext,                       void);
_Fn_(uint64_t   , getdents,                         void);
_Fn_(uint64_t   , getdirentries,                    void);
_Fn_(int        , getdtablesize,                    void);
_Fn_(gid_t      , getegid,                          void);
_Fn_(uid_t      , geteuid,                          void);
_Fn_(gid_t      , getgid,                           void);
_Fn_(int        , getgroups,                        int, gid_t []);
_Fn_(uint64_t   , getitimer,                        void);
_Fn_(char *     , getlogin,                         void);
_Fn_(int        , getlogin_r,                       char *, int);
_Fn_(int        , getpagesize,                      void);
_Fn_(uint64_t   , getpeername,                      void);
_Fn_(pid_t      , getppid,                          void);
_Fn_(uint64_t   , getpriority,                      void);
_Fn_(uint64_t   , getrlimit,                        void);
_Fn_(uint64_t   , getrusage,                        void);
_Fn_(int        , getsid,                           pid_t);
_Fn_(uint64_t   , getsockname,                      void);
_Fn_(uint64_t   , getsockopt,                       void);
_Fn_(uint64_t   , gettimeofday,                     void);
_Fn_(uid_t      , getuid,                           void);
_Fn_(uint64_t   , htonl,                            void);
_Fn_(uint64_t   , inet_ntop,                        void);
_Fn_(uint64_t   , ioctl,                            void);
_Fn_(uint64_t   , is_in_sandbox,                    void);
_Fn_(int        , issetugid,                        void);
_Fn_(uint64_t   , kevent,                           void);
_Fn_(int        , kill, __pid_t,                    int);
_Fn_(uint64_t   , kqueue,                           void);
_Fn_(uint64_t   , ksem_close,                       void);
_Fn_(uint64_t   , ksem_destroy,                     void);
_Fn_(uint64_t   , ksem_getvalue,                    void);
_Fn_(uint64_t   , ksem_init,                        void);
_Fn_(uint64_t   , ksem_open,                        void);
_Fn_(uint64_t   , ksem_post,                        void);
_Fn_(uint64_t   , ksem_timedwait,                   void);
_Fn_(uint64_t   , ksem_trywait,                     void);
_Fn_(uint64_t   , ksem_unlink,                      void);
_Fn_(uint64_t   , ksem_wait,                        void);
_Fn_(uint64_t   , ktimer_create,                    void);
_Fn_(uint64_t   , ktimer_delete,                    void);
_Fn_(uint64_t   , ktimer_getoverrun,                void);
_Fn_(uint64_t   , ktimer_gettime,                   void);
_Fn_(uint64_t   , ktimer_settime,                   void);
_Fn_(off_t      , lseek,                            int, off_t, int);
_Fn_(uint64_t   , lstat,                            void);
_Fn_(uint64_t   , madvise,                          void);
_Fn_(uint64_t   , mdbg_service,                     void);
_Fn_(uint64_t   , mincore,                          void);
_Fn_(uint64_t   , mkdir,                            void);
_Fn_(uint64_t   , mlock,                            void);
_Fn_(uint64_t   , mlockall,                         void);
_Fn_(void *     , mmap,                             void *, size_t, int, int, int, off_t);
_Fn_(uint64_t   , mprotect,                         void);
_Fn_(uint64_t   , msync,                            void);
_Fn_(uint64_t   , munlock,                          void);
_Fn_(uint64_t   , munlockall,                       void);
_Fn_(uint64_t   , munmap,                           void);
_Fn_(int        , nanosleep,                        const struct timespec *, struct timespec *);
_Fn_(uint64_t   , open,                             void);
_Fn_(uint64_t   , openintr,                         void);
_Fn_(int        , pause,                            void);
_Fn_(uint64_t   , physhm_open,                      void);
_Fn_(uint64_t   , physhm_unlink,                    void);
_Fn_(int        , pipe,                             int *);
_Fn_(uint64_t   , poll,                             void);
_Fn_(ssize_t    , pread,                            int, void *, size_t, off_t);
_Fn_(uint64_t   , preadv,                           void);
_Fn_(int        , pselect,                          int, fd_set *__restrict, fd_set *__restrict, fd_set *__restrict,
													const struct timespec *__restrict, const sigset_t *__restrict);

_Fn_(uint64_t   , pthread_atfork,                   void);
_Fn_(uint64_t   , pthread_attr_destroy,             void);
_Fn_(uint64_t   , pthread_attr_get_np,              void);
_Fn_(uint64_t   , pthread_attr_getaffinity_np,      void);
_Fn_(uint64_t   , pthread_attr_getdetachstate,      void);
_Fn_(uint64_t   , pthread_attr_getguardsize,        void);
_Fn_(uint64_t   , pthread_attr_getinheritsched,     void);
_Fn_(uint64_t   , pthread_attr_getschedparam,       void);
_Fn_(uint64_t   , pthread_attr_getschedpolicy,      void);
_Fn_(uint64_t   , pthread_attr_getscope,            void);
_Fn_(uint64_t   , pthread_attr_getsolosched_np,     void);
_Fn_(uint64_t   , pthread_attr_getstack,            void);
_Fn_(uint64_t   , pthread_attr_getstackaddr,        void);
_Fn_(uint64_t   , pthread_attr_getstacksize,        void);
_Fn_(uint64_t   , pthread_attr_init,                void);
_Fn_(uint64_t   , pthread_attr_setaffinity_np,      void);
_Fn_(uint64_t   , pthread_attr_setcreatesuspend_np, void);
_Fn_(uint64_t   , pthread_attr_setdetachstate,      void);
_Fn_(uint64_t   , pthread_attr_setguardsize,        void);
_Fn_(uint64_t   , pthread_attr_setinheritsched,     void);
_Fn_(uint64_t   , pthread_attr_setschedother_np,    void);
_Fn_(uint64_t   , pthread_attr_setschedparam,       void);
_Fn_(uint64_t   , pthread_attr_setschedpolicy,      void);
_Fn_(uint64_t   , pthread_attr_setscope,            void);
_Fn_(uint64_t   , pthread_attr_setsolosched_np,     void);
_Fn_(uint64_t   , pthread_attr_setstack,            void);
_Fn_(uint64_t   , pthread_attr_setstackaddr,        void);
_Fn_(uint64_t   , pthread_attr_setstacksize,        void);
_Fn_(uint64_t   , pthread_barrier_destroy,          void);
_Fn_(uint64_t   , pthread_barrier_init,             void);
_Fn_(uint64_t   , pthread_barrier_setname_np,       void);
_Fn_(uint64_t   , pthread_barrier_wait,             void);
_Fn_(uint64_t   , pthread_barrierattr_destroy,      void);
_Fn_(uint64_t   , pthread_barrierattr_getpshared,   void);
_Fn_(uint64_t   , pthread_barrierattr_init,         void);
_Fn_(uint64_t   , pthread_barrierattr_setpshared,   void);
_Fn_(uint64_t   , pthread_cancel,                   void);
_Fn_(uint64_t   , pthread_cleanup_pop,              void);
_Fn_(uint64_t   , pthread_cleanup_push,             void);
_Fn_(uint64_t   , pthread_cond_broadcast,           void);
_Fn_(uint64_t   , pthread_cond_destroy,             void);
_Fn_(uint64_t   , pthread_cond_init,                void);
_Fn_(uint64_t   , pthread_cond_reltimedwait_np,     void);
_Fn_(uint64_t   , pthread_cond_setname_np,          void);
_Fn_(uint64_t   , pthread_cond_signal,              void);
_Fn_(uint64_t   , pthread_cond_signalto_np,         void);
_Fn_(uint64_t   , pthread_cond_timedwait,           void);
_Fn_(uint64_t   , pthread_cond_wait,                void);
_Fn_(uint64_t   , pthread_condattr_destroy,         void);
_Fn_(uint64_t   , pthread_condattr_getclock,        void);
_Fn_(uint64_t   , pthread_condattr_getpshared,      void);
_Fn_(uint64_t   , pthread_condattr_init,            void);
_Fn_(uint64_t   , pthread_condattr_setclock,        void);
_Fn_(uint64_t   , pthread_condattr_setpshared,      void);
_Fn_(uint64_t   , pthread_create,                   void);
_Fn_(uint64_t   , pthread_create_name_np,           void);
_Fn_(uint64_t   , pthread_detach,                   void);
_Fn_(uint64_t   , pthread_equal,                    void);
_Fn_(uint64_t   , pthread_exit,                     void);
_Fn_(uint64_t   , pthread_get_specificarray_np,     void);
_Fn_(uint64_t   , pthread_get_user_context_np,      void);
_Fn_(uint64_t   , pthread_getaffinity_np,           void);
_Fn_(uint64_t   , pthread_getconcurrency,           void);
_Fn_(uint64_t   , pthread_getcpuclockid,            void);
_Fn_(uint64_t   , pthread_getname_np,               void);
_Fn_(uint64_t   , pthread_getprio,                  void);
_Fn_(uint64_t   , pthread_getschedparam,            void);
_Fn_(uint64_t   , pthread_getspecific,              void);
_Fn_(uint64_t   , pthread_getstack_np,              void);
_Fn_(uint64_t   , pthread_getthreadid_np,           void);
_Fn_(uint64_t   , pthread_join,                     void);
_Fn_(uint64_t   , pthread_key_create,               void);
_Fn_(uint64_t   , pthread_key_delete,               void);
_Fn_(int        , pthread_kill, __pthread_t,        int);
_Fn_(uint64_t   , pthread_main_np,                  void);
_Fn_(uint64_t   , pthread_multi_np,                 void);
_Fn_(uint64_t   , pthread_mutex_destroy,            void);
_Fn_(uint64_t   , pthread_mutex_getprioceiling,     void);
_Fn_(uint64_t   , pthread_mutex_getspinloops_np,    void);
_Fn_(uint64_t   , pthread_mutex_getyieldloops_np,   void);
_Fn_(uint64_t   , pthread_mutex_init,               void);
_Fn_(uint64_t   , pthread_mutex_init_for_mono,      void);
_Fn_(uint64_t   , pthread_mutex_isowned_np,         void);
_Fn_(uint64_t   , pthread_mutex_lock,               void);
_Fn_(uint64_t   , pthread_mutex_reltimedlock_np,    void);
_Fn_(uint64_t   , pthread_mutex_setname_np,         void);
_Fn_(uint64_t   , pthread_mutex_setprioceiling,     void);
_Fn_(uint64_t   , pthread_mutex_setspinloops_np,    void);
_Fn_(uint64_t   , pthread_mutex_setyieldloops_np,   void);
_Fn_(uint64_t   , pthread_mutex_timedlock,          void);
_Fn_(uint64_t   , pthread_mutex_trylock,            void);
_Fn_(uint64_t   , pthread_mutex_unlock,             void);
_Fn_(uint64_t   , pthread_mutexattr_destroy,        void);
_Fn_(uint64_t   , pthread_mutexattr_getkind_np,     void);
_Fn_(uint64_t   , pthread_mutexattr_getgen_np,      void);
_Fn_(uint64_t   , pthread_mutexattr_getprioceiling, void);
_Fn_(uint64_t   , pthread_mutexattr_getprotocol,    void);
_Fn_(uint64_t   , pthread_mutexattr_getpshared,     void);
_Fn_(uint64_t   , pthread_mutexattr_gettype,        void);
_Fn_(uint64_t   , pthread_mutexattr_init,           void);
_Fn_(uint64_t   , pthread_mutexattr_setgen_np,      void);
_Fn_(uint64_t   , pthread_mutexattr_setkind_np,     void);
_Fn_(uint64_t   , pthread_mutexattr_setprioceiling, void);
_Fn_(uint64_t   , pthread_mutexattr_setprotocol,    void);
_Fn_(uint64_t   , pthread_mutexattr_setpshared,     void);
_Fn_(uint64_t   , pthread_mutexattr_settype,        void);
_Fn_(uint64_t   , pthread_once,                     void);
_Fn_(uint64_t   , pthread_rename_np,                void);
_Fn_(uint64_t   , pthread_resume_all_np,            void);
_Fn_(uint64_t   , pthread_resume_np,                void);
_Fn_(uint64_t   , pthread_resume_user_context_np,   void);
_Fn_(uint64_t   , pthread_rwlock_destroy,           void);
_Fn_(uint64_t   , pthread_rwlock_init,              void);
_Fn_(uint64_t   , pthread_rwlock_rdlock,            void);
_Fn_(uint64_t   , pthread_rwlock_reltimedrdlock_np, void);
_Fn_(uint64_t   , pthread_rwlock_reltimedwrlock_np, void);
_Fn_(uint64_t   , pthread_rwlock_setname_np,        void);
_Fn_(uint64_t   , pthread_rwlock_timedrdlock,       void);
_Fn_(uint64_t   , pthread_rwlock_timedwrlock,       void);
_Fn_(uint64_t   , pthread_rwlock_tryrdlock,         void);
_Fn_(uint64_t   , pthread_rwlock_trywrlock,         void);
_Fn_(uint64_t   , pthread_rwlock_unlock,            void);
_Fn_(uint64_t   , pthread_rwlock_wrlock,            void);
_Fn_(uint64_t   , pthread_rwlockattr_destroy,       void);
_Fn_(uint64_t   , pthread_rwlockattr_getpshared,    void);
_Fn_(uint64_t   , pthread_rwlockattr_gettype_np,    void);
_Fn_(uint64_t   , pthread_rwlockattr_init,          void);
_Fn_(uint64_t   , pthread_rwlockattr_setpshared,    void);
_Fn_(uint64_t   , pthread_rwlockattr_settype_np,    void);
_Fn_(uint64_t   , pthread_self,                     void);
_Fn_(uint64_t   , pthread_set_defaultstacksize_np,  void);
_Fn_(uint64_t   , pthread_set_name_np,              void);
_Fn_(uint64_t   , pthread_set_user_context_np,      void);
_Fn_(uint64_t   , pthread_setaffinity_np,           void);
_Fn_(uint64_t   , pthread_setcancelstate,           void);
_Fn_(uint64_t   , pthread_setcanceltype,            void);
_Fn_(uint64_t   , pthread_setconcurrency,           void);
_Fn_(uint64_t   , pthread_setprio,                  void);
_Fn_(uint64_t   , pthread_setschedother_np,         void);
_Fn_(uint64_t   , pthread_setschedparam,            void);
_Fn_(uint64_t   , pthread_setspecific,              void);
_Fn_(int        , pthread_sigmask,                  int, const __sigset_t * __restrict, __sigset_t * __restrict);
_Fn_(uint64_t   , pthread_single_np,                void);
_Fn_(uint64_t   , pthread_spin_destroy,             void);
_Fn_(uint64_t   , pthread_spin_init,                void);
_Fn_(uint64_t   , pthread_spin_lock,                void);
_Fn_(uint64_t   , pthread_spin_trylock,             void);
_Fn_(uint64_t   , pthread_spin_unlock,              void);
_Fn_(uint64_t   , pthread_suspend_all_np,           void);
_Fn_(uint64_t   , pthread_suspend_np,               void);
_Fn_(uint64_t   , pthread_suspend_user_context_np,  void);
_Fn_(uint64_t   , pthread_switch_add_np,            void);
_Fn_(uint64_t   , pthread_switch_delete_np,         void);
_Fn_(uint64_t   , pthread_testcancel,               void);
_Fn_(uint64_t   , pthread_timedjoin_np,             void);
_Fn_(uint64_t   , pthread_yield,                    void);
_Fn_(ssize_t    , pwrite,                           int, const void *, size_t, off_t);
_Fn_(uint64_t   , pwritev,                          void);
_Fn_(int        , raise,                            int);
_Fn_(ssize_t    , read,                             int, void *, size_t);
_Fn_(uint64_t   , readv,                            void);
_Fn_(uint64_t   , recv,                             void);
_Fn_(uint64_t   , recvfrom,                         void);
_Fn_(uint64_t   , recvmsg,                          void);
_Fn_(int        , rename,                           const char *, const char *);
_Fn_(pid_t      , rfork_thread,                     int, void *, int (*)(void *), void *);
_Fn_(int        , rmdir,                            const char *);
_Fn_(uint64_t   , rtld_printf,                      void);
_Fn_(uint64_t   , rtprio_thread,                    void);

_Fn_(uint64_t   , sched_get_priority_max,           void);
_Fn_(uint64_t   , sched_get_priority_min,           void);
_Fn_(uint64_t   , sched_getparam,                   void);
_Fn_(uint64_t   , sched_getscheduler,               void);
_Fn_(uint64_t   , sched_rr_get_interval,            void);
_Fn_(uint64_t   , sched_setparam,                   void);
_Fn_(uint64_t   , sched_setscheduler,               void);
_Fn_(uint64_t   , sched_yield,                      void);
_Fn_(int        , select,                           int, fd_set *, fd_set *, fd_set *, struct timeval *);
_Fn_(uint64_t   , sem_close,                        void);
_Fn_(uint64_t   , sem_destroy,                      void);
_Fn_(uint64_t   , sem_getvalue,                     void);
_Fn_(uint64_t   , sem_init,                         void);
_Fn_(uint64_t   , sem_open,                         void);
_Fn_(uint64_t   , sem_post,                         void);
_Fn_(uint64_t   , sem_reltimedwait_np,              void);
_Fn_(uint64_t   , sem_setname,                      void);
_Fn_(uint64_t   , sem_timedwait,                    void);
_Fn_(uint64_t   , sem_trywait,                      void);
_Fn_(uint64_t   , sem_unlink,                       void);
_Fn_(uint64_t   , sem_wait,                         void);
_Fn_(uint64_t   , send,                             void);
_Fn_(uint64_t   , sendfile,                         void);
_Fn_(uint64_t   , sendmsg,                          void);
_Fn_(uint64_t   , sendto,                           void);
_Fn_(uint64_t   , set_phys_fmem_limit,              void);
_Fn_(uint64_t   , setcontext,                       void);
_Fn_(int        , setegid,                          gid_t);
_Fn_(int        , seteuid,                          uid_t);
_Fn_(int        , setgroups,                        int, const gid_t *);
_Fn_(uint64_t   , setitimer,                        void);
_Fn_(uint64_t   , setpriority,                      void);
_Fn_(int        , setregid,                         gid_t, gid_t);
_Fn_(int        , setreuid,                         uid_t, uid_t);
_Fn_(uint64_t   , setrlimit,                        void);
_Fn_(uint64_t   , setsockopt,                       void);
_Fn_(uint64_t   , settimeofday,                     void);
_Fn_(int        , setuid,                           uid_t);
_Fn_(uint64_t   , shm_open,                         void);
_Fn_(uint64_t   , shm_unlink,                       void);
_Fn_(uint64_t   , shutdown,                         void);
_Fn_(int        , sigaction,                        int, const struct sigaction * __restrict, struct sigaction * __restrict);
_Fn_(int        , sigaddset,                        sigset_t *, int);
#if __FIXED_SIGNAL
_Fn_(int        , sigaltstack,                      const stack_t  * __restrict, stack_  t * __restrict);
_Fn_(int        , sigwaitinfo,                      const sigset_t * __restrict, siginfo_t * __restrict);
_Fn_(int        , sigtimedwait,                     const sigset_t * __restrict, siginfo_t * __restrict, const struct timespec * __restrict);
#endif
_Fn_(int        , sigdelset,                        sigset_t *, int);
_Fn_(int        , sigemptyset,                      sigset_t *);
_Fn_(int        , sigfillset,                       sigset_t *);
_Fn_(int        , sigismember,                      const sigset_t *, int);
_Fn_(void       , siglongjmp,                       sigjmp_buf env,   int val);
_Fn_(__sighandler_t* ,                              signal, int, __sighandler_t *);
_Fn_(int        , sigpending,                       sigset_t *);
_Fn_(int        , sigprocmask,                      int, const sigset_t * __restrict, sigset_t * __restrict);
_Fn_(int        , sigqueue,                         __pid_t, int, const union sigval);
_Fn_(int        , sigreturn,                        const struct __ucontext *);
_Fn_(int        , sigsetjmp,                        sigjmp_buf env, int savemask);
_Fn_(int        , sigsuspend,                       const sigset_t *);
_Fn_(int        , sigwait,                          const sigset_t * __restrict, int * __restrict);
_Fn_(uint32_t   , sleep,                            uint32_t);
_Fn_(uint64_t   , socketpair,                       void);
_Fn_(uint64_t   , stat,                             void);
_Fn_(uint64_t   , swapcontext,                      void);
_Fn_(void       , sync,                             void);

int libkernel_init()
{
	int M_libkernel = __DLSYM_MODULE_ID_LIBKERNEL;
	if (__dlsym_init != 1) {
		return -1;
	}

	DYNLIB_RESOLVE(M_libkernel, __sys_debug_init);
	DYNLIB_RESOLVE(M_libkernel, __sys_dl_get_info);
	DYNLIB_RESOLVE(M_libkernel, __sys_dl_get_info_2);
	DYNLIB_RESOLVE(M_libkernel, __sys_dl_get_list);
	DYNLIB_RESOLVE(M_libkernel, __sys_dl_get_metadata);
	DYNLIB_RESOLVE(M_libkernel, __sys_dynlib_get_info_for_libdbg);
	DYNLIB_RESOLVE(M_libkernel, __sys_dynlib_get_list_for_libdbg);
	DYNLIB_RESOLVE(M_libkernel, __sys_dynlib_get_info2);
	DYNLIB_RESOLVE(M_libkernel, __sys_dynlib_get_list2);
	DYNLIB_RESOLVE(M_libkernel, __sys_dynlib_load_prx);
	DYNLIB_RESOLVE(M_libkernel, __sys_get_proc_type_info);
	DYNLIB_RESOLVE(M_libkernel, __sys_is_development_mode);
	DYNLIB_RESOLVE(M_libkernel, __sys_kqueueex);
	DYNLIB_RESOLVE(M_libkernel, __sys_namedobj_create);
	DYNLIB_RESOLVE(M_libkernel, __sys_namedobj_delete);
	DYNLIB_RESOLVE(M_libkernel, __sys_netabort);
	DYNLIB_RESOLVE(M_libkernel, __sys_netcontrol);
	DYNLIB_RESOLVE(M_libkernel, __sys_netgetiflist);
	DYNLIB_RESOLVE(M_libkernel, __sys_netgetsockinfo);
	DYNLIB_RESOLVE(M_libkernel, __sys_opmc_disable);
	DYNLIB_RESOLVE(M_libkernel, __sys_opmc_enable);
	DYNLIB_RESOLVE(M_libkernel, __sys_opmc_get_ctr);
	DYNLIB_RESOLVE(M_libkernel, __sys_opmc_get_hw);
	DYNLIB_RESOLVE(M_libkernel, __sys_opmc_set_ctl);
	DYNLIB_RESOLVE(M_libkernel, __sys_opmc_set_ctr);
	DYNLIB_RESOLVE(M_libkernel, __sys_opmc_set_hw);
	DYNLIB_RESOLVE(M_libkernel, __sys_osem_close);
	DYNLIB_RESOLVE(M_libkernel, __sys_osem_open);
	DYNLIB_RESOLVE(M_libkernel, __sys_randomized_path);
	DYNLIB_RESOLVE(M_libkernel, __sys_rdup);
	DYNLIB_RESOLVE(M_libkernel, __sys_regmgr_call);
	DYNLIB_RESOLVE(M_libkernel, __sys_set_uevt);
	DYNLIB_RESOLVE(M_libkernel, __sys_socketclose);
	DYNLIB_RESOLVE(M_libkernel, __sys_socketex);
	DYNLIB_RESOLVE(M_libkernel, __sys_test_debug_rwmem);
	DYNLIB_RESOLVE(M_libkernel, __sys_workaround8849);
	DYNLIB_RESOLVE(M_libkernel, _accept);
	DYNLIB_RESOLVE(M_libkernel, _bind);
	DYNLIB_RESOLVE(M_libkernel, _close);
	DYNLIB_RESOLVE(M_libkernel, _connect);
	DYNLIB_RESOLVE(M_libkernel, _dup2);
	DYNLIB_RESOLVE(M_libkernel, _execve);
	DYNLIB_RESOLVE(M_libkernel, _execvpe);
	DYNLIB_RESOLVE(M_libkernel, _exit);
	DYNLIB_RESOLVE(M_libkernel, _fcntl);
	DYNLIB_RESOLVE(M_libkernel, _fpathconf);
	DYNLIB_RESOLVE(M_libkernel, _fstat);
	DYNLIB_RESOLVE(M_libkernel, _fstatfs);
	DYNLIB_RESOLVE(M_libkernel, _getdirentries);
	DYNLIB_RESOLVE(M_libkernel, _getpeername);
	DYNLIB_RESOLVE(M_libkernel, _getsockname);
	DYNLIB_RESOLVE(M_libkernel, _getsockopt);
	DYNLIB_RESOLVE(M_libkernel, _ioctl);
	DYNLIB_RESOLVE(M_libkernel, _is_signal_return);
	DYNLIB_RESOLVE(M_libkernel, _listen);
	DYNLIB_RESOLVE(M_libkernel, _nanosleep);
	DYNLIB_RESOLVE(M_libkernel, _open);
	DYNLIB_RESOLVE(M_libkernel, _openat);
	DYNLIB_RESOLVE(M_libkernel, _read);
	DYNLIB_RESOLVE(M_libkernel, _readv);
	DYNLIB_RESOLVE(M_libkernel, _recvfrom);
	DYNLIB_RESOLVE(M_libkernel, _recvmsg);
	DYNLIB_RESOLVE(M_libkernel, _sceKernelRtldSetApplicationHeapAPI);
	DYNLIB_RESOLVE(M_libkernel, _sceKernelRtldThreadAtexitDecrement);
	DYNLIB_RESOLVE(M_libkernel, _sceKernelRtldThreadAtexitIncrement);
	DYNLIB_RESOLVE(M_libkernel, _sceKernelSetThreadDtors);
	DYNLIB_RESOLVE(M_libkernel, _sceKernelSetThreadAtexitCount);
	DYNLIB_RESOLVE(M_libkernel, _sceKernelSetThreadAtexitReport);
	DYNLIB_RESOLVE(M_libkernel, _sendmsg);
	DYNLIB_RESOLVE(M_libkernel, _sendto);
	DYNLIB_RESOLVE(M_libkernel, _setsockopt);
	DYNLIB_RESOLVE(M_libkernel, _sigaction);
	DYNLIB_RESOLVE(M_libkernel, _sigprocmask);
	DYNLIB_RESOLVE(M_libkernel, _sigsuspend);
	DYNLIB_RESOLVE(M_libkernel, _umtx_op);
	DYNLIB_RESOLVE(M_libkernel, _wait4);
	DYNLIB_RESOLVE(M_libkernel, _write);
	DYNLIB_RESOLVE(M_libkernel, _writev);
	DYNLIB_RESOLVE(M_libkernel, accept);
	DYNLIB_RESOLVE(M_libkernel, access);
	DYNLIB_RESOLVE(M_libkernel, bind);
	DYNLIB_RESOLVE(M_libkernel, blockpool_batch);
	DYNLIB_RESOLVE(M_libkernel, blockpool_map);
	DYNLIB_RESOLVE(M_libkernel, blockpool_open);
	DYNLIB_RESOLVE(M_libkernel, blockpool_unmap);
	DYNLIB_RESOLVE(M_libkernel, cfsetspeed);
	DYNLIB_RESOLVE(M_libkernel, chdir);
	DYNLIB_RESOLVE(M_libkernel, chflags);
	DYNLIB_RESOLVE(M_libkernel, chmod);
	DYNLIB_RESOLVE(M_libkernel, clock_getres);
	DYNLIB_RESOLVE(M_libkernel, clock_gettime);
	DYNLIB_RESOLVE(M_libkernel, clock_settime);
	DYNLIB_RESOLVE(M_libkernel, close);
	DYNLIB_RESOLVE(M_libkernel, connect);
	DYNLIB_RESOLVE(M_libkernel, cpuset_getaffinity);
	DYNLIB_RESOLVE(M_libkernel, cpuset_getid);
	DYNLIB_RESOLVE(M_libkernel, cpuset_setaffinity);
	DYNLIB_RESOLVE(M_libkernel, creat);
	DYNLIB_RESOLVE(M_libkernel, dlclose);
	DYNLIB_RESOLVE(M_libkernel, dlerror);
	DYNLIB_RESOLVE(M_libkernel, dlopen);
	DYNLIB_RESOLVE(M_libkernel, dup);
	DYNLIB_RESOLVE(M_libkernel, dup2);
	DYNLIB_RESOLVE(M_libkernel, dynlib_get_obj_member);
	DYNLIB_RESOLVE(M_libkernel, execv);
	DYNLIB_RESOLVE(M_libkernel, execve);
	DYNLIB_RESOLVE(M_libkernel, execvp);
	DYNLIB_RESOLVE(M_libkernel, fchflags);
	DYNLIB_RESOLVE(M_libkernel, fchmod);
	DYNLIB_RESOLVE(M_libkernel, fcntl);
	DYNLIB_RESOLVE(M_libkernel, flock);
	DYNLIB_RESOLVE(M_libkernel, fstat);
	DYNLIB_RESOLVE(M_libkernel, fsync);
	DYNLIB_RESOLVE(M_libkernel, fdatasync);
	DYNLIB_RESOLVE(M_libkernel, ftruncate);
	DYNLIB_RESOLVE(M_libkernel, futimes);
	DYNLIB_RESOLVE(M_libkernel, get_authinfo);
	DYNLIB_RESOLVE(M_libkernel, get_page_table_stats);
	DYNLIB_RESOLVE(M_libkernel, get_module_info_list);
	DYNLIB_RESOLVE(M_libkernel, get_sdk_compiled_version);
	DYNLIB_RESOLVE(M_libkernel, get_self_auth_info);
	DYNLIB_RESOLVE(M_libkernel, get_vm_map_timestamp);
	DYNLIB_RESOLVE(M_libkernel, getargc);
	DYNLIB_RESOLVE(M_libkernel, getargv);
	DYNLIB_RESOLVE(M_libkernel, getcontext);
	DYNLIB_RESOLVE(M_libkernel, getdents);
	DYNLIB_RESOLVE(M_libkernel, getdirentries);
	DYNLIB_RESOLVE(M_libkernel, getdtablesize);
	DYNLIB_RESOLVE(M_libkernel, getegid);
	DYNLIB_RESOLVE(M_libkernel, geteuid);
	DYNLIB_RESOLVE(M_libkernel, getgid);
	DYNLIB_RESOLVE(M_libkernel, getgroups);
	DYNLIB_RESOLVE(M_libkernel, getitimer);
	DYNLIB_RESOLVE(M_libkernel, getlogin);
	DYNLIB_RESOLVE(M_libkernel, getlogin_r);
	DYNLIB_RESOLVE(M_libkernel, getpagesize);
	DYNLIB_RESOLVE(M_libkernel, getpeername);
	DYNLIB_RESOLVE(M_libkernel, getpid);
	DYNLIB_RESOLVE(M_libkernel, getppid);
	DYNLIB_RESOLVE(M_libkernel, getpriority);
	DYNLIB_RESOLVE(M_libkernel, getrlimit);
	DYNLIB_RESOLVE(M_libkernel, getrusage);
	DYNLIB_RESOLVE(M_libkernel, getsid);
	DYNLIB_RESOLVE(M_libkernel, getsockname);
	DYNLIB_RESOLVE(M_libkernel, getsockopt);
	DYNLIB_RESOLVE(M_libkernel, gettimeofday);
	DYNLIB_RESOLVE(M_libkernel, getuid);
	DYNLIB_RESOLVE(M_libkernel, htonl);
	DYNLIB_RESOLVE(M_libkernel, htons);
	DYNLIB_RESOLVE(M_libkernel, inet_ntop);
	DYNLIB_RESOLVE(M_libkernel, inet_pton);
	DYNLIB_RESOLVE(M_libkernel, ioctl);
	DYNLIB_RESOLVE(M_libkernel, is_in_sandbox);
	DYNLIB_RESOLVE(M_libkernel, issetugid);
	DYNLIB_RESOLVE(M_libkernel, kevent);
	DYNLIB_RESOLVE(M_libkernel, kill);
	DYNLIB_RESOLVE(M_libkernel, kqueue);
	DYNLIB_RESOLVE(M_libkernel, ksem_close);
	DYNLIB_RESOLVE(M_libkernel, ksem_destroy);
	DYNLIB_RESOLVE(M_libkernel, ksem_getvalue);
	DYNLIB_RESOLVE(M_libkernel, ksem_init);
	DYNLIB_RESOLVE(M_libkernel, ksem_open);
	DYNLIB_RESOLVE(M_libkernel, ksem_post);
	DYNLIB_RESOLVE(M_libkernel, ksem_timedwait);
	DYNLIB_RESOLVE(M_libkernel, ksem_trywait);
	DYNLIB_RESOLVE(M_libkernel, ksem_unlink);
	DYNLIB_RESOLVE(M_libkernel, ksem_wait);
	DYNLIB_RESOLVE(M_libkernel, ktimer_create);
	DYNLIB_RESOLVE(M_libkernel, ktimer_delete);
	DYNLIB_RESOLVE(M_libkernel, ktimer_getoverrun);
	DYNLIB_RESOLVE(M_libkernel, ktimer_gettime);
	DYNLIB_RESOLVE(M_libkernel, ktimer_settime);
	DYNLIB_RESOLVE(M_libkernel, listen);
	DYNLIB_RESOLVE(M_libkernel, lseek);
	DYNLIB_RESOLVE(M_libkernel, lstat);
	DYNLIB_RESOLVE(M_libkernel, madvise);
	DYNLIB_RESOLVE(M_libkernel, mdbg_service);
	DYNLIB_RESOLVE(M_libkernel, mincore);
	DYNLIB_RESOLVE(M_libkernel, mkdir);
	DYNLIB_RESOLVE(M_libkernel, mlock);
	DYNLIB_RESOLVE(M_libkernel, mlockall);
	DYNLIB_RESOLVE(M_libkernel, mmap);
	DYNLIB_RESOLVE(M_libkernel, mprotect);
	DYNLIB_RESOLVE(M_libkernel, msync);
	DYNLIB_RESOLVE(M_libkernel, munlock);
	DYNLIB_RESOLVE(M_libkernel, munlockall);
	DYNLIB_RESOLVE(M_libkernel, munmap);
	DYNLIB_RESOLVE(M_libkernel, nanosleep);
////    DYNLIB_RESOLVE(M_libkernel, ntohl);     // *FIXME* macro^
////    DYNLIB_RESOLVE(M_libkernel, ntohs);
	DYNLIB_RESOLVE(M_libkernel, open);
	DYNLIB_RESOLVE(M_libkernel, openintr);
	DYNLIB_RESOLVE(M_libkernel, pause);
	DYNLIB_RESOLVE(M_libkernel, physhm_open);
	DYNLIB_RESOLVE(M_libkernel, physhm_unlink);
	DYNLIB_RESOLVE(M_libkernel, pipe);
	DYNLIB_RESOLVE(M_libkernel, poll);
	DYNLIB_RESOLVE(M_libkernel, pread);
	DYNLIB_RESOLVE(M_libkernel, preadv);
	DYNLIB_RESOLVE(M_libkernel, pselect);
	DYNLIB_RESOLVE(M_libkernel, pthread_atfork);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_get_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getaffinity_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getdetachstate);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getguardsize);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getinheritsched);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getschedparam);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getschedpolicy);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getscope);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getsolosched_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getstack);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getstackaddr);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_getstacksize);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setaffinity_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setcreatesuspend_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setdetachstate);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setguardsize);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setinheritsched);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setschedother_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setschedparam);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setschedpolicy);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setscope);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setsolosched_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setstack);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setstackaddr);
	DYNLIB_RESOLVE(M_libkernel, pthread_attr_setstacksize);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrier_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrier_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrier_setname_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrier_wait);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrierattr_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrierattr_getpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrierattr_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_barrierattr_setpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_cancel);
	DYNLIB_RESOLVE(M_libkernel, pthread_cleanup_pop);
	DYNLIB_RESOLVE(M_libkernel, pthread_cleanup_push);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_broadcast);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_reltimedwait_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_setname_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_signal);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_signalto_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_timedwait);
	DYNLIB_RESOLVE(M_libkernel, pthread_cond_wait);
	DYNLIB_RESOLVE(M_libkernel, pthread_condattr_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_condattr_getclock);
	DYNLIB_RESOLVE(M_libkernel, pthread_condattr_getpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_condattr_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_condattr_setclock);
	DYNLIB_RESOLVE(M_libkernel, pthread_condattr_setpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_create);
	DYNLIB_RESOLVE(M_libkernel, pthread_create_name_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_detach);
	DYNLIB_RESOLVE(M_libkernel, pthread_equal);
	DYNLIB_RESOLVE(M_libkernel, pthread_exit);
	DYNLIB_RESOLVE(M_libkernel, pthread_get_specificarray_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_get_user_context_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_getaffinity_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_getconcurrency);
	DYNLIB_RESOLVE(M_libkernel, pthread_getcpuclockid);
	DYNLIB_RESOLVE(M_libkernel, pthread_getname_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_getprio);
	DYNLIB_RESOLVE(M_libkernel, pthread_getschedparam);
	DYNLIB_RESOLVE(M_libkernel, pthread_getspecific);
	DYNLIB_RESOLVE(M_libkernel, pthread_getstack_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_getthreadid_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_join);
	DYNLIB_RESOLVE(M_libkernel, pthread_key_create);
	DYNLIB_RESOLVE(M_libkernel, pthread_key_delete);
	DYNLIB_RESOLVE(M_libkernel, pthread_kill);
	DYNLIB_RESOLVE(M_libkernel, pthread_main_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_multi_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_getprioceiling);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_getspinloops_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_getyieldloops_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_init_for_mono);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_isowned_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_lock);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_reltimedlock_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_setname_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_setprioceiling);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_setspinloops_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_setyieldloops_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_timedlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_trylock);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutex_unlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_getkind_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_getgen_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_getprioceiling);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_getprotocol);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_getpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_gettype);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_setgen_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_setkind_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_setprioceiling);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_setprotocol);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_setpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_mutexattr_settype);
	DYNLIB_RESOLVE(M_libkernel, pthread_once);
	DYNLIB_RESOLVE(M_libkernel, pthread_rename_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_resume_all_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_resume_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_resume_user_context_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_rdlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_reltimedrdlock_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_reltimedwrlock_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_setname_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_timedrdlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_timedwrlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_tryrdlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_trywrlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_unlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlock_wrlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlockattr_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlockattr_getpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlockattr_gettype_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlockattr_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlockattr_setpshared);
	DYNLIB_RESOLVE(M_libkernel, pthread_rwlockattr_settype_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_self);
	DYNLIB_RESOLVE(M_libkernel, pthread_set_defaultstacksize_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_set_name_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_set_user_context_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_setaffinity_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_setcancelstate);
	DYNLIB_RESOLVE(M_libkernel, pthread_setcanceltype);
	DYNLIB_RESOLVE(M_libkernel, pthread_setconcurrency);
	DYNLIB_RESOLVE(M_libkernel, pthread_setprio);
	DYNLIB_RESOLVE(M_libkernel, pthread_setschedother_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_setschedparam);
	DYNLIB_RESOLVE(M_libkernel, pthread_setspecific);
	DYNLIB_RESOLVE(M_libkernel, pthread_sigmask);
	DYNLIB_RESOLVE(M_libkernel, pthread_single_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_spin_destroy);
	DYNLIB_RESOLVE(M_libkernel, pthread_spin_init);
	DYNLIB_RESOLVE(M_libkernel, pthread_spin_lock);
	DYNLIB_RESOLVE(M_libkernel, pthread_spin_trylock);
	DYNLIB_RESOLVE(M_libkernel, pthread_spin_unlock);
	DYNLIB_RESOLVE(M_libkernel, pthread_suspend_all_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_suspend_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_suspend_user_context_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_switch_add_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_switch_delete_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_testcancel);
	DYNLIB_RESOLVE(M_libkernel, pthread_timedjoin_np);
	DYNLIB_RESOLVE(M_libkernel, pthread_yield);
	DYNLIB_RESOLVE(M_libkernel, pwrite);
	DYNLIB_RESOLVE(M_libkernel, pwritev);
	DYNLIB_RESOLVE(M_libkernel, raise);
	DYNLIB_RESOLVE(M_libkernel, read);
	DYNLIB_RESOLVE(M_libkernel, readv);
	DYNLIB_RESOLVE(M_libkernel, recv);
	DYNLIB_RESOLVE(M_libkernel, recvfrom);
	DYNLIB_RESOLVE(M_libkernel, recvmsg);
	DYNLIB_RESOLVE(M_libkernel, rename);
	DYNLIB_RESOLVE(M_libkernel, rfork_thread);
	DYNLIB_RESOLVE(M_libkernel, rmdir);
	DYNLIB_RESOLVE(M_libkernel, rtld_printf);
	DYNLIB_RESOLVE(M_libkernel, rtprio_thread);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddCpumodeEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddFileEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddGpuExceptionEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddHRTimerEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddProcessToCanvasMap);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddReadEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddTimerEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddUserEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddUserEventEdge);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddWriteEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddExternalTriggerEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddAmprEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteAmprEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAddAmprSystemEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteAmprSystemEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioCancelRequest);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioCancelRequests);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioDeleteRequest);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioDeleteRequests);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioInitializeImpl);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioInitializeParam);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioPollRequest);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioPollRequests);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioSetParam);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioSubmitReadCommands);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioSubmitReadCommandsMultiple);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioSubmitWriteCommands);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioSubmitWriteCommandsMultiple);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioWaitRequest);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAioWaitRequests);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateDirectMemory2);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateDirectMemoryForMiniApp);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateDirectMemoryForApp);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateMainDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateRemainingToolMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateToolMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAllocateTraceDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAvailableDirectMemorySize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAvailableFlexibleMemorySize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAvailableFlexibleMemorySizeForPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelAvailableToolMemorySize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelBacktraceSelf);
	DYNLIB_RESOLVE(M_libkernel, sceKernelBatchMap);
	DYNLIB_RESOLVE(M_libkernel, sceKernelBatchMap2);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCancelEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCancelSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCheckProsperoSdkVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCheckReachability);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCheckedReleaseDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelChmod);
	DYNLIB_RESOLVE(M_libkernel, sceKernelClearBootReqNotifyCount);
	DYNLIB_RESOLVE(M_libkernel, sceKernelClearEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelClearGameDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelClearMaxSocPowerConsumption);
	DYNLIB_RESOLVE(M_libkernel, sceKernelClockGetres);
	DYNLIB_RESOLVE(M_libkernel, sceKernelClockGettime);
	DYNLIB_RESOLVE(M_libkernel, sceKernelClose);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCloseEport);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCloseEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCloseSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelConfiguredFlexibleMemorySize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelConfiguredFlexibleMemorySizeForPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelConvertLocaltimeToUtc);
	DYNLIB_RESOLVE(M_libkernel, sceKernelConvertUtcToLocaltime);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCreateEport);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCreateEqueue);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCreateEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCreateSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugAcquireAndUpdateDebugRegister);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugGetAppStatus);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugGetPauseCount);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugGpuPaDebugIsInProgress);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugOutText);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugRaiseException);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugRaiseExceptionOnReleaseMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugRaiseExceptionWithContext);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugRaiseExceptionWithInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDebugReleaseDebugContext);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteCpumodeEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteEport);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteEqueue);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteFileEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteGpuExceptionEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteHRTimerEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteProcessFromCanvasMap);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteReadEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteTimerEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteUserEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteWriteEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDeleteExternalTriggerEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDirectMemoryQuery);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDirectMemoryQueryForId);
	DYNLIB_RESOLVE(M_libkernel, sceKernelDlsym);
	DYNLIB_RESOLVE(M_libkernel, sceKernelEnableDmemAliasing);
	DYNLIB_RESOLVE(M_libkernel, sceKernelEnableDmemAliasing2);
	DYNLIB_RESOLVE(M_libkernel, sceKernelEnablePthreadObjectCheck);
	DYNLIB_RESOLVE(M_libkernel, sceKernelError);
	DYNLIB_RESOLVE(M_libkernel, sceKernelEventLogInit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelEventLogPread);
	DYNLIB_RESOLVE(M_libkernel, sceKernelEventLogRead);
	DYNLIB_RESOLVE(M_libkernel, sceKernelEventLogWrite);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteSdkEventLog);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteSdkEventLogV);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFchmod);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFcntl);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFlock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFstat);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFsync);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFdatasync);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFtruncate);
	DYNLIB_RESOLVE(M_libkernel, sceKernelFutimes);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetAllowedSdkVersionOnSystem);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetAppCategoryType);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetAppInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetAppLibcData);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetAslrStatus);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetBioUsageAll);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetBackupRestoreMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetBackupRestoreModeOfNextBoot);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetBasicProductShape);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetBetaUpdateTestForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetBootReqNotifyCount);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCallRecord);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCompiledSdkVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCompiledSdkVersionByPath);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCompiledSdkVersionByPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetGenuineProsperoCompiledSdkVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetGenuineProsperoCompiledSdkVersionByPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPrefixVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProsperoCompiledSdkVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProsperoCompiledSdkVersionByPath);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProsperoCompiledSdkVersionByPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPs4CompiledSdkVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPs4CompiledSdkVersionByPath);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPs4CompiledSdkVersionByPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCanvasHandle);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCanvasHandleByApplicationLocalPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCanvasHandleByPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuCoreClock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuFrequency);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuTemperature);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuUsage);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuUsageAll);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuUsageProc);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuUsageProc2);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpuUsageThread);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpumode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCpumodeGame);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetCurrentCpu);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDataTransferMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDebugMenuMiniModeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDebugMenuModeForPsmForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDebugMenuModeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDefaultToolMemorySize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDirectMemorySize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDirectMemorySizeForPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetDirectMemoryType);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetEventData);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetEventError);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetEventFflags);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetEventFilter);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetEventId);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetEventUserData);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetExecutableModuleHandle);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetExtLibcHandle);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetFakeFinalizeMenuForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetFlagedUpdaterForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetForceUpdateModeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetFsSandboxRandomWord);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetGenuineProsperoSystemSwVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetGPI);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetGPO);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetHwFeatureInfoForDecid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetIdPs);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetIdTableCurrentCount);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetIpcPath);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetKnobs);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetLibkernelTextLocation);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetMainSocId);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetModuleInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetModuleInfoForUnwind);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetModuleInfoFromAddr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetModuleInfoInternal);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetModuleList);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetModuleListInternal);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetOpenPsIdForSystem);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPageTableStats);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPageTableStatsForPid);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPagingStatsOfAllObjects);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPagingStatsOfAllThreads);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProcParam);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProcessAbiType);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProcessName);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProcessType);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProcessTime);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProcessTimeCounter);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProcessTimeCounterFrequency);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProductCode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProductStr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetProsperoSystemSwVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPrtAperture);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPs4SystemSwVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPsmIntdevModeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPsnAccessTraceLogForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetQafExpirationTimeNotafterForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetQafExpirationTimeNotbeforeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetQafGenerationForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetQafNameForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetRenderingMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetResidentCount);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetResidentFmemCount);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSafemode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSanitizerMallocReplace);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSanitizerMallocReplaceExternal);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSanitizerNewReplace);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSanitizerNewReplaceExternal);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSocClock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSocPowerConsumption);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSocSensorTemperature);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSpecialIForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSubsysId);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSubsysSubId);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSystemLevelDebuggerModeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSystemSwBeta);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetSystemSwVersion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetThreadName);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetToolMemoryRange);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetTraceMemoryStats);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetTscFrequency);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUniversalMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenDataExecutionForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenExpirationTimeNotafterForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenExpirationTimeNotbeforeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenFakeSharefactoryForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenFlagedUpdaterForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenNpEnvSwitchingForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenSaveDataRepairForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenStoreModeForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenUseSoftwagnerForAcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenUseSoftwagnerForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetUtokenWeakenedPortRestrictionForRcmgr);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetVrCaptureSize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetdents);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetdirentries);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGettimeofday);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGettimezone);
	DYNLIB_RESOLVE(M_libkernel, sceKernelHasNeoMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelHwHasOpticalOut);
	DYNLIB_RESOLVE(M_libkernel, sceKernelHwHasWlanBt);
	DYNLIB_RESOLVE(M_libkernel, sceKernelHwGetBdDriveInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccControlBDPowerState);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccControlUSBPowerState);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetBDPowerState);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetCPMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetCpuInfoBit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetPowerNumberOfBootShutdown);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetPowerOperatingTime);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetPowerUpCause);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetThermalAlert);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccGetUSBPowerState);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccIndicatorBootDone);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccIndicatorShutdown);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccIndicatorStandby);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccIndicatorStandbyBoot);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccIndicatorStandbyShutdown);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccNotifyBootStatus);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccNvsFlush);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccReadPowerBootMessage);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccSetBuzzer);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccSetCPMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccSetCpuInfoBit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccSetDownloadMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIccSetPriorityBuzzer);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInstallExceptionHandler);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalGetKmemStatistics);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalGetMapStatistics);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalHeapPrintBacktraceWithModuleInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPrintBacktraceWithModuleInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalMapDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalMapNamedDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalMemoryGetAvailableSize);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalMemoryGetModuleSegmentInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalResumeDirectMemoryRelease);
	DYNLIB_RESOLVE(M_libkernel, sceKernelInternalSuspendDirectMemoryRelease);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsAddressSanitizerEnabled);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsThreadSanitizerEnabled);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsAllowedToSelectDvdRegion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsAuthenticNeo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsCEX);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsDebuggerAttached);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsDevKit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsGenuineCEX);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsGenuineCronosCex);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsGenuineDevKit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsGenuineKratosCex);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsGenuineN);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsGenuineTestKit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsInSandbox);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsKratos);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsMainOnStanbyMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsMainOnStandbyMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsNeoMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsPs4Process);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsStack);
	DYNLIB_RESOLVE(M_libkernel, sceKernelIsTestKit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelKernelHeapUsage);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLoadStartModule);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLoadStartModuleForSysmodule);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLseek);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLwfsAllocateBlock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLwfsLseek);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLwfsSetAttribute);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLwfsTrimBlock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelLwfsWrite);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapDirectMemory2);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapFlexibleMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapNamedDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapNamedFlexibleMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapNamedSystemFlexibleMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapSanitizerShadowMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapToolMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapTraceMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMemoryPoolBatch);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMemoryPoolCommit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMemoryPoolDecommit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMemoryPoolExpand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMemoryPoolGetBlockStats);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMemoryPoolMove);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMemoryPoolReserve);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMkdir);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMlock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMlockall);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMmap);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMprotect);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMsync);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMtypeprotect);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMunlock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMunlockall);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMunmap);
	DYNLIB_RESOLVE(M_libkernel, sceKernelNanosleep);
	DYNLIB_RESOLVE(M_libkernel, sceKernelNormalizePath);
	DYNLIB_RESOLVE(M_libkernel, sceKernelNotifyAppStateChanged);
	DYNLIB_RESOLVE(M_libkernel, sceKernelNotifySystemSuspendResumeProgress);
	DYNLIB_RESOLVE(M_libkernel, sceKernelNotifySystemSuspendStart);
	DYNLIB_RESOLVE(M_libkernel, sceKernelOpen);
	DYNLIB_RESOLVE(M_libkernel, sceKernelOpenInternal);
	DYNLIB_RESOLVE(M_libkernel, sceKernelOpenEport);
	DYNLIB_RESOLVE(M_libkernel, sceKernelOpenEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelOpenSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPltTrap);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPollEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPollSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPread);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPreadv);
	DYNLIB_RESOLVE(M_libkernel, sceKernelProtectDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelProtectDirectMemoryForPID);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPwrite);
	DYNLIB_RESOLVE(M_libkernel, sceKernelPwritev);
	DYNLIB_RESOLVE(M_libkernel, sceKernelQueryMemoryProtection);
	DYNLIB_RESOLVE(M_libkernel, sceKernelQueryToolMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelQueryTraceMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRaiseException);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRandomizedPath);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRdup);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRead);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReadTsc);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReadv);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReboot);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReleaseDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReleaseFlexibleMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReleaseToolMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReleaseTraceDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRemoveExceptionHandler);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRename);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReportUnpatchedFunctionCall);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReserveSystemDirectMemory);
	DYNLIB_RESOLVE(M_libkernel, sceKernelReserveVirtualRange);
	DYNLIB_RESOLVE(M_libkernel, sceKernelResumeDirectMemoryRelease);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRmdir);
	DYNLIB_RESOLVE(M_libkernel, sceKernelRtldControl);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSandboxPath);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSendNotificationRequest);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetAppInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetAppLibcData);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetBackupRestoreMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetBaseModeClock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetBesteffort);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetBootReqNotify);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetCallRecord);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetCanvasHandle);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetCompressionAttribute);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetCpumodeGame);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetDataTransferMode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetFsstParam);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetGPI);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetGPO);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetGameDirectMemoryLimit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetGpuCu);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetKnobs);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetMemoryPstate);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetNativeModeClock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetNeoModeClock);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetPhysFmemLimit);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetProcessName);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetProcessProperty);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetProcessPropertyString);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetPrtAperture);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetSafemode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetTimezoneInfo);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetVirtualRangeName);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSetVmContainer);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSettimeofday);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSignalSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSleep);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSlvNotifyError);
	DYNLIB_RESOLVE(M_libkernel, sceKernelStat);
	DYNLIB_RESOLVE(M_libkernel, sceKernelStopUnloadModule);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSuspendDirectMemoryRelease);
	DYNLIB_RESOLVE(M_libkernel, sceKernelSync);
	DYNLIB_RESOLVE(M_libkernel, sceKernelTerminateSysCore);
	DYNLIB_RESOLVE(M_libkernel, sceKernelTitleWorkaroundIsEnabled);
	DYNLIB_RESOLVE(M_libkernel, sceKernelTitleWorkdaroundIsEnabled);
	DYNLIB_RESOLVE(M_libkernel, sceKernelTraceMemoryTypeProtect);
	DYNLIB_RESOLVE(M_libkernel, sceKernelTriggerEport);
	DYNLIB_RESOLVE(M_libkernel, sceKernelTriggerUserEvent);
	DYNLIB_RESOLVE(M_libkernel, sceKernelTruncate);
	DYNLIB_RESOLVE(M_libkernel, sceKernelUnlink);
	DYNLIB_RESOLVE(M_libkernel, sceKernelUsleep);
	DYNLIB_RESOLVE(M_libkernel, sceKernelUtimes);
	DYNLIB_RESOLVE(M_libkernel, sceKernelUuidCreate);
	DYNLIB_RESOLVE(M_libkernel, sceKernelVirtualQuery);
	DYNLIB_RESOLVE(M_libkernel, sceKernelVirtualQueryAll);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWaitEqueue);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWaitEventFlag);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWaitSema);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWrite);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWritev);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGiveDirectMemoryToMapper);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCallIndirectBuffer);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCallIndirectBuffer2);
	DYNLIB_RESOLVE(M_libkernel, sceKernelCallIndirectBuffer3);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWaitCommandBufferCompletion);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteEventQueueOnCompletionCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteMapCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteMapCommand2);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteMapWithGpuMaskIdCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteMapDirectCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteMapDirectWithGpuMaskIdCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteMultiMapCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteMultiMapWithGpuMaskIdCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteRemapCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteRemapWithGpuMaskIdCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteUnmapCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteModifyProtectCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteModifyMtypeProtectCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteModifyProtectWithGpuMaskIdCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteModifyMtypeProtectWithGpuMaskIdCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteWriteAddressCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteWriteCounterCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteWaitOnAddressCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelWriteWaitOnCounterCommand);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapperGetParam);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapperVirtualQuery);
	DYNLIB_RESOLVE(M_libkernel, sceDebugKernelMapperQueryDmemOffset);
	DYNLIB_RESOLVE(M_libkernel, sceDebugKernelMapperDebugSuspend);
	DYNLIB_RESOLVE(M_libkernel, sceDebugKernelMapperDebugResume);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapperDebugSuspend);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapperDebugResume);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapperQueryPa);
	DYNLIB_RESOLVE(M_libkernel, sceKernelMapperQueryDmemOffset);
	DYNLIB_RESOLVE(M_libkernel, sceKernelYieldCpumode);
	DYNLIB_RESOLVE(M_libkernel, sceKernelGetPhysPageSize);
	DYNLIB_RESOLVE(M_libkernel, sceLibcMspaceCreateForMonoMutex);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAtfork);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGet);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetaffinity);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetdetachstate);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetguardsize);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetinheritsched);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetschedparam);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetschedpolicy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetscope);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetsolosched);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetstack);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetstackaddr);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrGetstacksize);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetaffinity);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetcreatesuspend);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetdetachstate);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetguardsize);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetinheritsched);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetschedother);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetschedparam);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetschedpolicy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetscope);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetstack);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetstackaddr);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetstacksize);
	DYNLIB_RESOLVE(M_libkernel, scePthreadAttrSetsolosched);
	DYNLIB_RESOLVE(M_libkernel, scePthreadBarrierDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadBarrierInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadBarrierWait);
	DYNLIB_RESOLVE(M_libkernel, scePthreadBarrierattrDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadBarrierattrGetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadBarrierattrInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadBarrierattrSetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCancel);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondBroadcast);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondSignal);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondSignalto);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondTimedwait);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondWait);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondattrDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondattrGetclock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondattrGetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondattrInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondattrSetclock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCondattrSetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadCreate);
	DYNLIB_RESOLVE(M_libkernel, scePthreadDetach);
	DYNLIB_RESOLVE(M_libkernel, scePthreadEqual);
	DYNLIB_RESOLVE(M_libkernel, scePthreadExit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetaffinity);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetconcurrency);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetcpuclockid);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetname);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetprio);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetschedparam);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetspecific);
	DYNLIB_RESOLVE(M_libkernel, scePthreadGetthreadid);
	DYNLIB_RESOLVE(M_libkernel, scePthreadJoin);
	DYNLIB_RESOLVE(M_libkernel, scePthreadKeyCreate);
	DYNLIB_RESOLVE(M_libkernel, scePthreadKeyDelete);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMain);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMulti);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexGetprioceiling);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexGetspinloops);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexGetyieldloops);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexInitForInternalLibc);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexIsowned);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexLock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexSetprioceiling);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexSetspinloops);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexSetyieldloops);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexTimedlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexTrylock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexUnlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrGetgen);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrGetkind);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrGetprioceiling);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrGetprotocol);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrGetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrGettype);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrInitForInternalLibc);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrSetgen);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrSetkind);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrSetprioceiling);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrSetprotocol);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrSetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadMutexattrSettype);
	DYNLIB_RESOLVE(M_libkernel, scePthreadOnce);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRename);
	DYNLIB_RESOLVE(M_libkernel, scePthreadResume);
	DYNLIB_RESOLVE(M_libkernel, scePthreadResumeAll);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockRdlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockTimedrdlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockTimedwrlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockTryrdlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockTrywrlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockUnlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockWrlock);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockattrDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockattrGetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockattrInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockattrSetpshared);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockattrGettype);
	DYNLIB_RESOLVE(M_libkernel, scePthreadRwlockattrSettype);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSelf);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSemInit);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSemDestroy);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSemTimedwait);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSemGetvalue);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSemPost);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSemTrywait);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSemWait);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetBesteffort);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetDefaultstacksize);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetName);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetaffinity);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetcancelstate);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetcanceltype);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetconcurrency);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetprio);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetschedother);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetschedparam);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSetspecific);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSingle);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSuspend);
	DYNLIB_RESOLVE(M_libkernel, scePthreadSuspendAll);
	DYNLIB_RESOLVE(M_libkernel, scePthreadTestcancel);
	DYNLIB_RESOLVE(M_libkernel, scePthreadTimedjoin);
	DYNLIB_RESOLVE(M_libkernel, scePthreadYield);
	DYNLIB_RESOLVE(M_libkernel, sched_get_priority_max);
	DYNLIB_RESOLVE(M_libkernel, sched_get_priority_min);
	DYNLIB_RESOLVE(M_libkernel, sched_getparam);
	DYNLIB_RESOLVE(M_libkernel, sched_getscheduler);
	DYNLIB_RESOLVE(M_libkernel, sched_rr_get_interval);
	DYNLIB_RESOLVE(M_libkernel, sched_setparam);
	DYNLIB_RESOLVE(M_libkernel, sched_setscheduler);
	DYNLIB_RESOLVE(M_libkernel, sched_yield);
	DYNLIB_RESOLVE(M_libkernel, select);
	DYNLIB_RESOLVE(M_libkernel, sem_close);
	DYNLIB_RESOLVE(M_libkernel, sem_destroy);
	DYNLIB_RESOLVE(M_libkernel, sem_getvalue);
	DYNLIB_RESOLVE(M_libkernel, sem_init);
	DYNLIB_RESOLVE(M_libkernel, sem_open);
	DYNLIB_RESOLVE(M_libkernel, sem_post);
	DYNLIB_RESOLVE(M_libkernel, sem_reltimedwait_np);
	DYNLIB_RESOLVE(M_libkernel, sem_setname);
	DYNLIB_RESOLVE(M_libkernel, sem_timedwait);
	DYNLIB_RESOLVE(M_libkernel, sem_trywait);
	DYNLIB_RESOLVE(M_libkernel, sem_unlink);
	DYNLIB_RESOLVE(M_libkernel, sem_wait);
	DYNLIB_RESOLVE(M_libkernel, send);
	DYNLIB_RESOLVE(M_libkernel, sendfile);
	DYNLIB_RESOLVE(M_libkernel, sendmsg);
	DYNLIB_RESOLVE(M_libkernel, sendto);
	DYNLIB_RESOLVE(M_libkernel, set_phys_fmem_limit);
	DYNLIB_RESOLVE(M_libkernel, setcontext);
	DYNLIB_RESOLVE(M_libkernel, setegid);
	DYNLIB_RESOLVE(M_libkernel, seteuid);
	DYNLIB_RESOLVE(M_libkernel, setgroups);
	DYNLIB_RESOLVE(M_libkernel, setitimer);
	DYNLIB_RESOLVE(M_libkernel, setpriority);
	DYNLIB_RESOLVE(M_libkernel, setregid);
	DYNLIB_RESOLVE(M_libkernel, setreuid);
	DYNLIB_RESOLVE(M_libkernel, setrlimit);
	DYNLIB_RESOLVE(M_libkernel, setsockopt);
	DYNLIB_RESOLVE(M_libkernel, settimeofday);
	DYNLIB_RESOLVE(M_libkernel, setuid);
	DYNLIB_RESOLVE(M_libkernel, shm_open);
	DYNLIB_RESOLVE(M_libkernel, shm_unlink);
	DYNLIB_RESOLVE(M_libkernel, shutdown);
	DYNLIB_RESOLVE(M_libkernel, sigaction);
	DYNLIB_RESOLVE(M_libkernel, sigaddset);
	DYNLIB_RESOLVE(M_libkernel, sigdelset);
	DYNLIB_RESOLVE(M_libkernel, sigemptyset);
	DYNLIB_RESOLVE(M_libkernel, sigfillset);
	DYNLIB_RESOLVE(M_libkernel, sigismember);
	DYNLIB_RESOLVE(M_libkernel, siglongjmp);
	DYNLIB_RESOLVE(M_libkernel, signal);
	DYNLIB_RESOLVE(M_libkernel, sigpending);
	DYNLIB_RESOLVE(M_libkernel, sigprocmask);
	DYNLIB_RESOLVE(M_libkernel, sigqueue);
	DYNLIB_RESOLVE(M_libkernel, sigreturn);
	DYNLIB_RESOLVE(M_libkernel, sigsetjmp);
	DYNLIB_RESOLVE(M_libkernel, sigsuspend);
	DYNLIB_RESOLVE(M_libkernel, sigwait);
	DYNLIB_RESOLVE(M_libkernel, sleep);
	DYNLIB_RESOLVE(M_libkernel, socket);
//    DYNLIB_RESOLVE(M_libkernel, socketpair);
//    DYNLIB_RESOLVE(M_libkernel, stat);
//    DYNLIB_RESOLVE(M_libkernel, swapcontext);
//    DYNLIB_RESOLVE(M_libkernel, sync);
//    DYNLIB_RESOLVE(M_libkernel, sysKernelGetIntdevModeForRcmgr);
//    DYNLIB_RESOLVE(M_libkernel, sysKernelGetIntdevModeForInternalLibc);
//    DYNLIB_RESOLVE(M_libkernel, sysKernelGetLowerLimitUpdVersion);
//    DYNLIB_RESOLVE(M_libkernel, sysKernelGetLowerLimitSysexVersion);
//    DYNLIB_RESOLVE(M_libkernel, sysKernelGetManufacturingMode);
//    DYNLIB_RESOLVE(M_libkernel, sysKernelGetUpdVersion);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelGetSystemExVersion);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelGetUpdVersion);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelGetAutoUpdateVersion);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelGetBuildNumber);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelIsExperimentalBeta);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelReserve2mbPage);
//    DYNLIB_RESOLVE(M_libkernel, sysarch);
//    DYNLIB_RESOLVE(M_libkernel, sysconf);
	DYNLIB_RESOLVE(M_libkernel, sysctl);
	DYNLIB_RESOLVE(M_libkernel, sysctlbyname);
//    DYNLIB_RESOLVE(M_libkernel, sysctlnametomib);
//    DYNLIB_RESOLVE(M_libkernel, system);
//    DYNLIB_RESOLVE(M_libkernel, tcdrain);
//    DYNLIB_RESOLVE(M_libkernel, tcflow);
//    DYNLIB_RESOLVE(M_libkernel, tcflush);
//    DYNLIB_RESOLVE(M_libkernel, tcgetattr);
//    DYNLIB_RESOLVE(M_libkernel, tcgetpgrp);
//    DYNLIB_RESOLVE(M_libkernel, tcgetsid);
//    DYNLIB_RESOLVE(M_libkernel, tcsendbreak);
//    DYNLIB_RESOLVE(M_libkernel, tcsetattr);
//    DYNLIB_RESOLVE(M_libkernel, tcsetpgrp);
//    DYNLIB_RESOLVE(M_libkernel, tcsetsid);
//    DYNLIB_RESOLVE(M_libkernel, truncate);
//    DYNLIB_RESOLVE(M_libkernel, unlink);
//    DYNLIB_RESOLVE(M_libkernel, usleep);
//    DYNLIB_RESOLVE(M_libkernel, utimes);
//    DYNLIB_RESOLVE(M_libkernel, uuidgen);
//    DYNLIB_RESOLVE(M_libkernel, wait);
//    DYNLIB_RESOLVE(M_libkernel, wait3);
//    DYNLIB_RESOLVE(M_libkernel, waitpid);
//    DYNLIB_RESOLVE(M_libkernel, write);
//    DYNLIB_RESOLVE(M_libkernel, writev);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelIsCronos);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelUseCronosKura);
//    DYNLIB_RESOLVE(M_libkernel, sceKernelUseCronosStreaming);
////  DYNLIB_RESOLVE(M_libkernel, errno);     // *? will need to be done manually if you really don't just use macro #define errno (* __error)
//    DYNLIB_RESOLVE(M_libkernel, environ);
//    DYNLIB_RESOLVE(M_libkernel, sigcode_addr);
//
	DYNLIB_RESOLVE(M_libkernel, __error);

	return 0;
}
